### ISSUE TITLE
Failed to start in Dev Containers

### ISSUE THREAD

**Issue by jerryshia** [Azure-Samples/openai-secure-ui-js#2]
**Describe the issue:**
When running the project in `VS Code Dev Containers`, it fails to start.

![image](https://github.com/user-attachments/assets/8e87ad8f-1a0c-4465-85be-cbf0f0031a25)

**Repro Steps:**

1. Click the `Dev Containers` button in [readme](https://github.com/Azure-Samples/openai-secure-ui-js/blob/main/README.md#use-a-vscode-dev-container). 

**Environment:**

- azd version 1.10.1 (commit 31409a33266fb4a5fdbb644bc83988e725d6c7c9)
- OS: VS Code Dev Containers

**Expected behavior:**
The project runs successfully in dev container environment.

@hemarina and @sinedied for notification.

**Comment by sinedied** [comment]
@jerryshia this is most likely a temporary issue, as you can see in the logs it's AZD that fails installing

**Comment by jerryshia** [comment]
@sinedied We tested this issue with 4 machines, and 2 of them were able to open it successfully, while the other 2 consistently encountered the above issue. Is there any way to completely avoid this type of issue?

**Comment by sinedied** [comment]
Did you try in Codespaces?
Looking at the error, it's an SSL version issue which means you may have an outdated package on this machine (could be cached), or using a misconfigured proxy. That's why GH is rejecting the connection.
There's not much I can do on my side unfortunately

**Comment by jerryshia** [comment]
The issue has been verified and will no longer occur. I will close it.
