### ISSUE TITLE
Fail to run `azd up`

### ISSUE THREAD

**Issue by jerryshia** [Azure-Samples/openai-secure-ui-js#3]
**Describe the issue:**
When running `azd up`, the following error occurs:
![image](https://github.com/user-attachments/assets/e0fc65d2-b775-44b9-9962-6ce7af6d38c9)

**Repro Steps:**

1. Run `azd init -t openai-secure-ui-js`.
2. Run `azd auth login`.
3. Run `azd up`.

**Environment:**

- azd version 1.10.1 (commit 31409a33266fb4a5fdbb644bc83988e725d6c7c9)
- OS: Windows

**Expected behavior:**
Run `azd up` successful.

@hemarina and @sinedied for notification.

**Comment by sinedied** [comment]
@jerryshia `npm install` needs to be ran first before being able to deploy the application. I can add it to the `prepackage` hook if needed

**Comment by jerryshia** [comment]
@sinedied I ran `npm install` before running `azd up` and it works. I think it is necessary to add it to the `prepackage`.
